default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  username: deploy
  password: secret

test:
  <<: *default
  database: wallet_test

development:
  <<: *default
  database: wallet_dev

production:
  <<: *default
  database: wallet
